eureka:
  client:
    service-url:
      defaultZone: http://localhost:8890/eureka/
server:
  port: 8892

# spring.application.name 这个在以后的服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: serviceClient
