spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 配置git仓库地址
          uri: https://github.com/forezp/SpringcloudConfig/
          # 配置仓库路径
          searchPaths: respo
          # 访问git仓库的用户名
          username:
          # 访问git仓库的密码
          password:
      # 配置仓库分支
      label: master
server:
  port: 8896

#在默认设置下，Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为。
#否则被抛出 connection refused:connect 异常
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
